/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 10.0.0 -fPIC -Os) */

(* dynports =  1  *)
(* src = "../RAM/Ram.v:1" *)
module \$paramod\Ram\RAM_WIDTH=6\ADDR_SIZE=2 (clk, state, reset_L, enable, addr_out, addr_in, data_in, data_out_c);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  (* src = "../RAM/Ram.v:7" *)
  input [1:0] addr_in;
  (* src = "../RAM/Ram.v:7" *)
  input [1:0] addr_out;
  (* src = "../RAM/Ram.v:4" *)
  input clk;
  (* src = "../RAM/Ram.v:6" *)
  input [5:0] data_in;
  (* src = "../RAM/Ram.v:8" *)
  output [5:0] data_out_c;
  (* src = "../RAM/Ram.v:4" *)
  input enable;
  (* src = "../RAM/Ram.v:11" *)
  wire [31:0] i;
  wire [5:0] \mem[0] ;
  wire [5:0] \mem[1] ;
  wire [5:0] \mem[2] ;
  wire [5:0] \mem[3] ;
  (* src = "../RAM/Ram.v:4" *)
  input reset_L;
  (* src = "../RAM/Ram.v:5" *)
  input [1:0] state;
  NOT _212_ (
    .A(state[1]),
    .Y(_181_)
  );
  NOT _213_ (
    .A(\mem[3] [0]),
    .Y(_182_)
  );
  NOT _214_ (
    .A(\mem[3] [1]),
    .Y(_183_)
  );
  NOT _215_ (
    .A(\mem[3] [2]),
    .Y(_184_)
  );
  NOT _216_ (
    .A(\mem[3] [3]),
    .Y(_185_)
  );
  NOT _217_ (
    .A(\mem[3] [4]),
    .Y(_186_)
  );
  NOT _218_ (
    .A(\mem[3] [5]),
    .Y(_187_)
  );
  NOT _219_ (
    .A(\mem[0] [0]),
    .Y(_188_)
  );
  NOT _220_ (
    .A(\mem[0] [1]),
    .Y(_189_)
  );
  NOT _221_ (
    .A(\mem[0] [2]),
    .Y(_190_)
  );
  NOT _222_ (
    .A(\mem[0] [3]),
    .Y(_191_)
  );
  NOT _223_ (
    .A(\mem[0] [4]),
    .Y(_192_)
  );
  NOT _224_ (
    .A(\mem[0] [5]),
    .Y(_193_)
  );
  NOT _225_ (
    .A(reset_L),
    .Y(_194_)
  );
  NOT _226_ (
    .A(addr_in[0]),
    .Y(_195_)
  );
  NOT _227_ (
    .A(addr_in[1]),
    .Y(_196_)
  );
  NOT _228_ (
    .A(data_in[0]),
    .Y(_197_)
  );
  NOT _229_ (
    .A(data_in[1]),
    .Y(_198_)
  );
  NOT _230_ (
    .A(data_in[2]),
    .Y(_199_)
  );
  NOT _231_ (
    .A(data_in[3]),
    .Y(_200_)
  );
  NOT _232_ (
    .A(data_in[4]),
    .Y(_201_)
  );
  NOT _233_ (
    .A(data_in[5]),
    .Y(_202_)
  );
  NAND _234_ (
    .A(state[1]),
    .B(reset_L),
    .Y(_203_)
  );
  NOT _235_ (
    .A(_203_),
    .Y(_204_)
  );
  NOR _236_ (
    .A(addr_in[1]),
    .B(_203_),
    .Y(_205_)
  );
  NOT _237_ (
    .A(_205_),
    .Y(_206_)
  );
  NOR _238_ (
    .A(addr_in[0]),
    .B(_206_),
    .Y(_207_)
  );
  NAND _239_ (
    .A(_195_),
    .B(_205_),
    .Y(_208_)
  );
  NAND _240_ (
    .A(\mem[0] [0]),
    .B(reset_L),
    .Y(_209_)
  );
  NOT _241_ (
    .A(_209_),
    .Y(_210_)
  );
  NOR _242_ (
    .A(_207_),
    .B(_210_),
    .Y(_211_)
  );
  NOR _243_ (
    .A(data_in[0]),
    .B(_208_),
    .Y(_024_)
  );
  NOR _244_ (
    .A(_211_),
    .B(_024_),
    .Y(_000_)
  );
  NAND _245_ (
    .A(\mem[0] [1]),
    .B(reset_L),
    .Y(_025_)
  );
  NOT _246_ (
    .A(_025_),
    .Y(_026_)
  );
  NOR _247_ (
    .A(_207_),
    .B(_026_),
    .Y(_027_)
  );
  NOR _248_ (
    .A(data_in[1]),
    .B(_208_),
    .Y(_028_)
  );
  NOR _249_ (
    .A(_027_),
    .B(_028_),
    .Y(_001_)
  );
  NAND _250_ (
    .A(\mem[0] [2]),
    .B(reset_L),
    .Y(_029_)
  );
  NOT _251_ (
    .A(_029_),
    .Y(_030_)
  );
  NOR _252_ (
    .A(_207_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _253_ (
    .A(data_in[2]),
    .B(_208_),
    .Y(_032_)
  );
  NOR _254_ (
    .A(_031_),
    .B(_032_),
    .Y(_002_)
  );
  NAND _255_ (
    .A(\mem[0] [3]),
    .B(reset_L),
    .Y(_033_)
  );
  NOT _256_ (
    .A(_033_),
    .Y(_034_)
  );
  NOR _257_ (
    .A(_207_),
    .B(_034_),
    .Y(_035_)
  );
  NOR _258_ (
    .A(data_in[3]),
    .B(_208_),
    .Y(_036_)
  );
  NOR _259_ (
    .A(_035_),
    .B(_036_),
    .Y(_003_)
  );
  NAND _260_ (
    .A(\mem[0] [4]),
    .B(reset_L),
    .Y(_037_)
  );
  NOT _261_ (
    .A(_037_),
    .Y(_038_)
  );
  NOR _262_ (
    .A(_207_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _263_ (
    .A(data_in[4]),
    .B(_208_),
    .Y(_040_)
  );
  NOR _264_ (
    .A(_039_),
    .B(_040_),
    .Y(_004_)
  );
  NAND _265_ (
    .A(\mem[0] [5]),
    .B(reset_L),
    .Y(_041_)
  );
  NOT _266_ (
    .A(_041_),
    .Y(_042_)
  );
  NOR _267_ (
    .A(_207_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _268_ (
    .A(data_in[5]),
    .B(_208_),
    .Y(_044_)
  );
  NOR _269_ (
    .A(_043_),
    .B(_044_),
    .Y(_005_)
  );
  NAND _270_ (
    .A(addr_in[0]),
    .B(addr_in[1]),
    .Y(_045_)
  );
  NOT _271_ (
    .A(_045_),
    .Y(_046_)
  );
  NOR _272_ (
    .A(_181_),
    .B(_045_),
    .Y(_047_)
  );
  NOR _273_ (
    .A(_194_),
    .B(_047_),
    .Y(_048_)
  );
  NAND _274_ (
    .A(\mem[3] [0]),
    .B(_048_),
    .Y(_049_)
  );
  NOR _275_ (
    .A(_197_),
    .B(_203_),
    .Y(_050_)
  );
  NAND _276_ (
    .A(_046_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _277_ (
    .A(_049_),
    .B(_051_),
    .Y(_018_)
  );
  NAND _278_ (
    .A(\mem[3] [1]),
    .B(_048_),
    .Y(_052_)
  );
  NOR _279_ (
    .A(_198_),
    .B(_203_),
    .Y(_053_)
  );
  NAND _280_ (
    .A(_046_),
    .B(_053_),
    .Y(_054_)
  );
  NAND _281_ (
    .A(_052_),
    .B(_054_),
    .Y(_019_)
  );
  NAND _282_ (
    .A(\mem[3] [2]),
    .B(_048_),
    .Y(_055_)
  );
  NOR _283_ (
    .A(_199_),
    .B(_203_),
    .Y(_056_)
  );
  NAND _284_ (
    .A(_046_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _285_ (
    .A(_055_),
    .B(_057_),
    .Y(_020_)
  );
  NAND _286_ (
    .A(\mem[3] [3]),
    .B(_048_),
    .Y(_058_)
  );
  NOR _287_ (
    .A(_200_),
    .B(_203_),
    .Y(_059_)
  );
  NAND _288_ (
    .A(_046_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _289_ (
    .A(_058_),
    .B(_060_),
    .Y(_021_)
  );
  NAND _290_ (
    .A(\mem[3] [4]),
    .B(_048_),
    .Y(_061_)
  );
  NOR _291_ (
    .A(_201_),
    .B(_203_),
    .Y(_062_)
  );
  NAND _292_ (
    .A(_046_),
    .B(_062_),
    .Y(_063_)
  );
  NAND _293_ (
    .A(_061_),
    .B(_063_),
    .Y(_022_)
  );
  NAND _294_ (
    .A(\mem[3] [5]),
    .B(_048_),
    .Y(_064_)
  );
  NOR _295_ (
    .A(_202_),
    .B(_203_),
    .Y(_065_)
  );
  NAND _296_ (
    .A(_046_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _297_ (
    .A(_064_),
    .B(_066_),
    .Y(_023_)
  );
  NOR _298_ (
    .A(addr_in[0]),
    .B(_196_),
    .Y(_067_)
  );
  NAND _299_ (
    .A(_195_),
    .B(addr_in[1]),
    .Y(_068_)
  );
  NOR _300_ (
    .A(_203_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _301_ (
    .A(_204_),
    .B(_067_),
    .Y(_070_)
  );
  NAND _302_ (
    .A(\mem[2] [0]),
    .B(reset_L),
    .Y(_071_)
  );
  NOT _303_ (
    .A(_071_),
    .Y(_072_)
  );
  NOR _304_ (
    .A(_069_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _305_ (
    .A(data_in[0]),
    .B(_070_),
    .Y(_074_)
  );
  NOR _306_ (
    .A(_073_),
    .B(_074_),
    .Y(_012_)
  );
  NAND _307_ (
    .A(\mem[2] [1]),
    .B(reset_L),
    .Y(_075_)
  );
  NOT _308_ (
    .A(_075_),
    .Y(_076_)
  );
  NOR _309_ (
    .A(_069_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _310_ (
    .A(data_in[1]),
    .B(_070_),
    .Y(_078_)
  );
  NOR _311_ (
    .A(_077_),
    .B(_078_),
    .Y(_013_)
  );
  NAND _312_ (
    .A(\mem[2] [2]),
    .B(reset_L),
    .Y(_079_)
  );
  NOT _313_ (
    .A(_079_),
    .Y(_080_)
  );
  NOR _314_ (
    .A(_069_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _315_ (
    .A(data_in[2]),
    .B(_070_),
    .Y(_082_)
  );
  NOR _316_ (
    .A(_081_),
    .B(_082_),
    .Y(_014_)
  );
  NAND _317_ (
    .A(\mem[2] [3]),
    .B(reset_L),
    .Y(_083_)
  );
  NOT _318_ (
    .A(_083_),
    .Y(_084_)
  );
  NOR _319_ (
    .A(_069_),
    .B(_084_),
    .Y(_085_)
  );
  NOR _320_ (
    .A(data_in[3]),
    .B(_070_),
    .Y(_086_)
  );
  NOR _321_ (
    .A(_085_),
    .B(_086_),
    .Y(_015_)
  );
  NAND _322_ (
    .A(\mem[2] [4]),
    .B(reset_L),
    .Y(_087_)
  );
  NOT _323_ (
    .A(_087_),
    .Y(_088_)
  );
  NOR _324_ (
    .A(_069_),
    .B(_088_),
    .Y(_089_)
  );
  NOR _325_ (
    .A(data_in[4]),
    .B(_070_),
    .Y(_090_)
  );
  NOR _326_ (
    .A(_089_),
    .B(_090_),
    .Y(_016_)
  );
  NAND _327_ (
    .A(\mem[2] [5]),
    .B(reset_L),
    .Y(_091_)
  );
  NOT _328_ (
    .A(_091_),
    .Y(_092_)
  );
  NOR _329_ (
    .A(_069_),
    .B(_092_),
    .Y(_093_)
  );
  NOR _330_ (
    .A(data_in[5]),
    .B(_070_),
    .Y(_094_)
  );
  NOR _331_ (
    .A(_093_),
    .B(_094_),
    .Y(_017_)
  );
  NAND _332_ (
    .A(addr_in[0]),
    .B(_205_),
    .Y(_095_)
  );
  NAND _333_ (
    .A(reset_L),
    .B(\mem[1] [0]),
    .Y(_096_)
  );
  NAND _334_ (
    .A(_095_),
    .B(_096_),
    .Y(_097_)
  );
  NOT _335_ (
    .A(_097_),
    .Y(_098_)
  );
  NOR _336_ (
    .A(data_in[0]),
    .B(_095_),
    .Y(_099_)
  );
  NOR _337_ (
    .A(_098_),
    .B(_099_),
    .Y(_006_)
  );
  NAND _338_ (
    .A(reset_L),
    .B(\mem[1] [1]),
    .Y(_100_)
  );
  NAND _339_ (
    .A(_095_),
    .B(_100_),
    .Y(_101_)
  );
  NOT _340_ (
    .A(_101_),
    .Y(_102_)
  );
  NOR _341_ (
    .A(data_in[1]),
    .B(_095_),
    .Y(_103_)
  );
  NOR _342_ (
    .A(_102_),
    .B(_103_),
    .Y(_007_)
  );
  NAND _343_ (
    .A(reset_L),
    .B(\mem[1] [2]),
    .Y(_104_)
  );
  NAND _344_ (
    .A(_095_),
    .B(_104_),
    .Y(_105_)
  );
  NOT _345_ (
    .A(_105_),
    .Y(_106_)
  );
  NOR _346_ (
    .A(data_in[2]),
    .B(_095_),
    .Y(_107_)
  );
  NOR _347_ (
    .A(_106_),
    .B(_107_),
    .Y(_008_)
  );
  NAND _348_ (
    .A(reset_L),
    .B(\mem[1] [3]),
    .Y(_108_)
  );
  NAND _349_ (
    .A(_095_),
    .B(_108_),
    .Y(_109_)
  );
  NOT _350_ (
    .A(_109_),
    .Y(_110_)
  );
  NOR _351_ (
    .A(data_in[3]),
    .B(_095_),
    .Y(_111_)
  );
  NOR _352_ (
    .A(_110_),
    .B(_111_),
    .Y(_009_)
  );
  NAND _353_ (
    .A(reset_L),
    .B(\mem[1] [4]),
    .Y(_112_)
  );
  NAND _354_ (
    .A(_095_),
    .B(_112_),
    .Y(_113_)
  );
  NOT _355_ (
    .A(_113_),
    .Y(_114_)
  );
  NOR _356_ (
    .A(data_in[4]),
    .B(_095_),
    .Y(_115_)
  );
  NOR _357_ (
    .A(_114_),
    .B(_115_),
    .Y(_010_)
  );
  NAND _358_ (
    .A(reset_L),
    .B(\mem[1] [5]),
    .Y(_116_)
  );
  NAND _359_ (
    .A(_095_),
    .B(_116_),
    .Y(_117_)
  );
  NOT _360_ (
    .A(_117_),
    .Y(_118_)
  );
  NOR _361_ (
    .A(data_in[5]),
    .B(_095_),
    .Y(_119_)
  );
  NOR _362_ (
    .A(_118_),
    .B(_119_),
    .Y(_011_)
  );
  NAND _363_ (
    .A(enable),
    .B(state[0]),
    .Y(_120_)
  );
  NOR _364_ (
    .A(\mem[2] [0]),
    .B(addr_out[0]),
    .Y(_121_)
  );
  NAND _365_ (
    .A(_182_),
    .B(addr_out[0]),
    .Y(_122_)
  );
  NAND _366_ (
    .A(addr_out[1]),
    .B(_122_),
    .Y(_123_)
  );
  NOR _367_ (
    .A(_121_),
    .B(_123_),
    .Y(_124_)
  );
  NAND _368_ (
    .A(addr_out[0]),
    .B(\mem[1] [0]),
    .Y(_125_)
  );
  NOT _369_ (
    .A(_125_),
    .Y(_126_)
  );
  NOR _370_ (
    .A(_188_),
    .B(addr_out[0]),
    .Y(_127_)
  );
  NOR _371_ (
    .A(_126_),
    .B(_127_),
    .Y(_128_)
  );
  NOR _372_ (
    .A(addr_out[1]),
    .B(_128_),
    .Y(_129_)
  );
  NOR _373_ (
    .A(_124_),
    .B(_129_),
    .Y(_130_)
  );
  NOR _374_ (
    .A(_120_),
    .B(_130_),
    .Y(data_out_c[0])
  );
  NOR _375_ (
    .A(\mem[2] [1]),
    .B(addr_out[0]),
    .Y(_131_)
  );
  NAND _376_ (
    .A(_183_),
    .B(addr_out[0]),
    .Y(_132_)
  );
  NAND _377_ (
    .A(addr_out[1]),
    .B(_132_),
    .Y(_133_)
  );
  NOR _378_ (
    .A(_131_),
    .B(_133_),
    .Y(_134_)
  );
  NAND _379_ (
    .A(addr_out[0]),
    .B(\mem[1] [1]),
    .Y(_135_)
  );
  NOT _380_ (
    .A(_135_),
    .Y(_136_)
  );
  NOR _381_ (
    .A(_189_),
    .B(addr_out[0]),
    .Y(_137_)
  );
  NOR _382_ (
    .A(_136_),
    .B(_137_),
    .Y(_138_)
  );
  NOR _383_ (
    .A(addr_out[1]),
    .B(_138_),
    .Y(_139_)
  );
  NOR _384_ (
    .A(_134_),
    .B(_139_),
    .Y(_140_)
  );
  NOR _385_ (
    .A(_120_),
    .B(_140_),
    .Y(data_out_c[1])
  );
  NOR _386_ (
    .A(\mem[2] [2]),
    .B(addr_out[0]),
    .Y(_141_)
  );
  NAND _387_ (
    .A(_184_),
    .B(addr_out[0]),
    .Y(_142_)
  );
  NAND _388_ (
    .A(addr_out[1]),
    .B(_142_),
    .Y(_143_)
  );
  NOR _389_ (
    .A(_141_),
    .B(_143_),
    .Y(_144_)
  );
  NAND _390_ (
    .A(addr_out[0]),
    .B(\mem[1] [2]),
    .Y(_145_)
  );
  NOT _391_ (
    .A(_145_),
    .Y(_146_)
  );
  NOR _392_ (
    .A(_190_),
    .B(addr_out[0]),
    .Y(_147_)
  );
  NOR _393_ (
    .A(_146_),
    .B(_147_),
    .Y(_148_)
  );
  NOR _394_ (
    .A(addr_out[1]),
    .B(_148_),
    .Y(_149_)
  );
  NOR _395_ (
    .A(_144_),
    .B(_149_),
    .Y(_150_)
  );
  NOR _396_ (
    .A(_120_),
    .B(_150_),
    .Y(data_out_c[2])
  );
  NOR _397_ (
    .A(\mem[2] [3]),
    .B(addr_out[0]),
    .Y(_151_)
  );
  NAND _398_ (
    .A(_185_),
    .B(addr_out[0]),
    .Y(_152_)
  );
  NAND _399_ (
    .A(addr_out[1]),
    .B(_152_),
    .Y(_153_)
  );
  NOR _400_ (
    .A(_151_),
    .B(_153_),
    .Y(_154_)
  );
  NAND _401_ (
    .A(addr_out[0]),
    .B(\mem[1] [3]),
    .Y(_155_)
  );
  NOT _402_ (
    .A(_155_),
    .Y(_156_)
  );
  NOR _403_ (
    .A(_191_),
    .B(addr_out[0]),
    .Y(_157_)
  );
  NOR _404_ (
    .A(_156_),
    .B(_157_),
    .Y(_158_)
  );
  NOR _405_ (
    .A(addr_out[1]),
    .B(_158_),
    .Y(_159_)
  );
  NOR _406_ (
    .A(_154_),
    .B(_159_),
    .Y(_160_)
  );
  NOR _407_ (
    .A(_120_),
    .B(_160_),
    .Y(data_out_c[3])
  );
  NOR _408_ (
    .A(\mem[2] [4]),
    .B(addr_out[0]),
    .Y(_161_)
  );
  NAND _409_ (
    .A(_186_),
    .B(addr_out[0]),
    .Y(_162_)
  );
  NAND _410_ (
    .A(addr_out[1]),
    .B(_162_),
    .Y(_163_)
  );
  NOR _411_ (
    .A(_161_),
    .B(_163_),
    .Y(_164_)
  );
  NAND _412_ (
    .A(addr_out[0]),
    .B(\mem[1] [4]),
    .Y(_165_)
  );
  NOT _413_ (
    .A(_165_),
    .Y(_166_)
  );
  NOR _414_ (
    .A(_192_),
    .B(addr_out[0]),
    .Y(_167_)
  );
  NOR _415_ (
    .A(_166_),
    .B(_167_),
    .Y(_168_)
  );
  NOR _416_ (
    .A(addr_out[1]),
    .B(_168_),
    .Y(_169_)
  );
  NOR _417_ (
    .A(_164_),
    .B(_169_),
    .Y(_170_)
  );
  NOR _418_ (
    .A(_120_),
    .B(_170_),
    .Y(data_out_c[4])
  );
  NOR _419_ (
    .A(\mem[2] [5]),
    .B(addr_out[0]),
    .Y(_171_)
  );
  NAND _420_ (
    .A(_187_),
    .B(addr_out[0]),
    .Y(_172_)
  );
  NAND _421_ (
    .A(addr_out[1]),
    .B(_172_),
    .Y(_173_)
  );
  NOR _422_ (
    .A(_171_),
    .B(_173_),
    .Y(_174_)
  );
  NAND _423_ (
    .A(addr_out[0]),
    .B(\mem[1] [5]),
    .Y(_175_)
  );
  NOT _424_ (
    .A(_175_),
    .Y(_176_)
  );
  NOR _425_ (
    .A(_193_),
    .B(addr_out[0]),
    .Y(_177_)
  );
  NOR _426_ (
    .A(_176_),
    .B(_177_),
    .Y(_178_)
  );
  NOR _427_ (
    .A(addr_out[1]),
    .B(_178_),
    .Y(_179_)
  );
  NOR _428_ (
    .A(_174_),
    .B(_179_),
    .Y(_180_)
  );
  NOR _429_ (
    .A(_120_),
    .B(_180_),
    .Y(data_out_c[5])
  );
  DFF _430_ (
    .C(clk),
    .D(_000_),
    .Q(\mem[0] [0])
  );
  DFF _431_ (
    .C(clk),
    .D(_001_),
    .Q(\mem[0] [1])
  );
  DFF _432_ (
    .C(clk),
    .D(_002_),
    .Q(\mem[0] [2])
  );
  DFF _433_ (
    .C(clk),
    .D(_003_),
    .Q(\mem[0] [3])
  );
  DFF _434_ (
    .C(clk),
    .D(_004_),
    .Q(\mem[0] [4])
  );
  DFF _435_ (
    .C(clk),
    .D(_005_),
    .Q(\mem[0] [5])
  );
  DFF _436_ (
    .C(clk),
    .D(_018_),
    .Q(\mem[3] [0])
  );
  DFF _437_ (
    .C(clk),
    .D(_019_),
    .Q(\mem[3] [1])
  );
  DFF _438_ (
    .C(clk),
    .D(_020_),
    .Q(\mem[3] [2])
  );
  DFF _439_ (
    .C(clk),
    .D(_021_),
    .Q(\mem[3] [3])
  );
  DFF _440_ (
    .C(clk),
    .D(_022_),
    .Q(\mem[3] [4])
  );
  DFF _441_ (
    .C(clk),
    .D(_023_),
    .Q(\mem[3] [5])
  );
  DFF _442_ (
    .C(clk),
    .D(_012_),
    .Q(\mem[2] [0])
  );
  DFF _443_ (
    .C(clk),
    .D(_013_),
    .Q(\mem[2] [1])
  );
  DFF _444_ (
    .C(clk),
    .D(_014_),
    .Q(\mem[2] [2])
  );
  DFF _445_ (
    .C(clk),
    .D(_015_),
    .Q(\mem[2] [3])
  );
  DFF _446_ (
    .C(clk),
    .D(_016_),
    .Q(\mem[2] [4])
  );
  DFF _447_ (
    .C(clk),
    .D(_017_),
    .Q(\mem[2] [5])
  );
  DFF _448_ (
    .C(clk),
    .D(_006_),
    .Q(\mem[1] [0])
  );
  DFF _449_ (
    .C(clk),
    .D(_007_),
    .Q(\mem[1] [1])
  );
  DFF _450_ (
    .C(clk),
    .D(_008_),
    .Q(\mem[1] [2])
  );
  DFF _451_ (
    .C(clk),
    .D(_009_),
    .Q(\mem[1] [3])
  );
  DFF _452_ (
    .C(clk),
    .D(_010_),
    .Q(\mem[1] [4])
  );
  DFF _453_ (
    .C(clk),
    .D(_011_),
    .Q(\mem[1] [5])
  );
  assign i = 32'd4;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "fifo_cond.v:3" *)
module fifo_cond(clk, reset_L, enable2, buffer_empty, buffer_full, push, pop, data_in, data_out_c, error_c, almost_empty_c, almost_full_c, empty_c, full_out_c);
  (* src = "fifo_cond.v:62" *)
  wire _000_;
  (* src = "fifo_cond.v:62" *)
  wire _001_;
  (* src = "fifo_cond.v:62" *)
  wire [1:0] _002_;
  (* src = "fifo_cond.v:62" *)
  wire [1:0] _003_;
  (* src = "fifo_cond.v:62" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  (* src = "fifo_cond.v:16" *)
  output almost_empty_c;
  (* src = "fifo_cond.v:17" *)
  output almost_full_c;
  (* src = "fifo_cond.v:44" *)
  wire almost_full_f;
  (* src = "fifo_cond.v:8" *)
  input [1:0] buffer_empty;
  (* src = "fifo_cond.v:9" *)
  input [1:0] buffer_full;
  (* src = "fifo_cond.v:5" *)
  input clk;
  (* src = "fifo_cond.v:12" *)
  input [5:0] data_in;
  (* src = "fifo_cond.v:14" *)
  output [5:0] data_out_c;
  (* src = "fifo_cond.v:18" *)
  output empty_c;
  (* src = "fifo_cond.v:44" *)
  wire empty_f;
  (* src = "fifo_cond.v:40" *)
  wire enable;
  (* src = "fifo_cond.v:7" *)
  input enable2;
  (* src = "fifo_cond.v:33" *)
  wire error;
  (* src = "fifo_cond.v:15" *)
  output error_c;
  (* src = "fifo_cond.v:29" *)
  wire [1:0] flop_rd;
  (* src = "fifo_cond.v:26" *)
  wire [1:0] flop_wr;
  (* src = "fifo_cond.v:44" *)
  wire full_f;
  (* src = "fifo_cond.v:19" *)
  output full_out_c;
  (* src = "fifo_cond.v:11" *)
  input pop;
  (* src = "fifo_cond.v:10" *)
  input push;
  (* src = "fifo_cond.v:6" *)
  input reset_L;
  (* src = "fifo_cond.v:38" *)
  wire [1:0] state;
  NOT _094_ (
    .A(almost_full_f),
    .Y(_025_)
  );
  NOT _095_ (
    .A(push),
    .Y(_026_)
  );
  NOT _096_ (
    .A(error_c),
    .Y(_027_)
  );
  NOT _097_ (
    .A(full_f),
    .Y(_028_)
  );
  NOT _098_ (
    .A(reset_L),
    .Y(_029_)
  );
  NOT _099_ (
    .A(flop_rd[0]),
    .Y(_030_)
  );
  NOT _100_ (
    .A(flop_wr[0]),
    .Y(_031_)
  );
  NOT _101_ (
    .A(buffer_empty[1]),
    .Y(_032_)
  );
  NAND _102_ (
    .A(pop),
    .B(_027_),
    .Y(_033_)
  );
  NOT _103_ (
    .A(_033_),
    .Y(_034_)
  );
  NOR _104_ (
    .A(empty_f),
    .B(full_f),
    .Y(_035_)
  );
  NOR _105_ (
    .A(push),
    .B(empty_f),
    .Y(_036_)
  );
  NOR _106_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  NAND _107_ (
    .A(push),
    .B(_027_),
    .Y(_038_)
  );
  NOR _108_ (
    .A(_026_),
    .B(_033_),
    .Y(_039_)
  );
  NAND _109_ (
    .A(_034_),
    .B(_037_),
    .Y(_040_)
  );
  NOR _110_ (
    .A(pop),
    .B(_038_),
    .Y(_041_)
  );
  NAND _111_ (
    .A(full_f),
    .B(_041_),
    .Y(_042_)
  );
  NAND _112_ (
    .A(_040_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _113_ (
    .A(error_c),
    .B(_043_),
    .Y(_044_)
  );
  NOR _114_ (
    .A(_029_),
    .B(_044_),
    .Y(error)
  );
  NOR _115_ (
    .A(_030_),
    .B(flop_wr[0]),
    .Y(_045_)
  );
  NAND _116_ (
    .A(flop_rd[0]),
    .B(_031_),
    .Y(_046_)
  );
  NOR _117_ (
    .A(flop_rd[0]),
    .B(_031_),
    .Y(_047_)
  );
  NAND _118_ (
    .A(_030_),
    .B(flop_wr[0]),
    .Y(_048_)
  );
  NOR _119_ (
    .A(_045_),
    .B(_047_),
    .Y(_049_)
  );
  NAND _120_ (
    .A(_046_),
    .B(_048_),
    .Y(_050_)
  );
  NOR _121_ (
    .A(flop_rd[1]),
    .B(flop_wr[1]),
    .Y(_051_)
  );
  NOT _122_ (
    .A(_051_),
    .Y(_052_)
  );
  NAND _123_ (
    .A(flop_rd[1]),
    .B(flop_wr[1]),
    .Y(_053_)
  );
  NOT _124_ (
    .A(_053_),
    .Y(_054_)
  );
  NAND _125_ (
    .A(_052_),
    .B(_053_),
    .Y(_055_)
  );
  NOR _126_ (
    .A(_051_),
    .B(_054_),
    .Y(_056_)
  );
  NOR _127_ (
    .A(_050_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _128_ (
    .A(_049_),
    .B(_055_),
    .Y(_058_)
  );
  NOR _129_ (
    .A(buffer_empty[1]),
    .B(_047_),
    .Y(_059_)
  );
  NAND _130_ (
    .A(_032_),
    .B(_048_),
    .Y(_060_)
  );
  NOR _131_ (
    .A(_032_),
    .B(_048_),
    .Y(_061_)
  );
  NAND _132_ (
    .A(buffer_empty[1]),
    .B(_047_),
    .Y(_062_)
  );
  NOR _133_ (
    .A(_059_),
    .B(_061_),
    .Y(_063_)
  );
  NAND _134_ (
    .A(_060_),
    .B(_062_),
    .Y(_064_)
  );
  NOR _135_ (
    .A(_055_),
    .B(_063_),
    .Y(_065_)
  );
  NOR _136_ (
    .A(_056_),
    .B(_064_),
    .Y(_066_)
  );
  NOR _137_ (
    .A(_065_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _138_ (
    .A(_050_),
    .B(_067_),
    .Y(_068_)
  );
  NAND _139_ (
    .A(buffer_empty[0]),
    .B(_049_),
    .Y(_069_)
  );
  NOR _140_ (
    .A(buffer_empty[0]),
    .B(_067_),
    .Y(_070_)
  );
  NAND _141_ (
    .A(_068_),
    .B(_069_),
    .Y(_071_)
  );
  NOR _142_ (
    .A(_070_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _143_ (
    .A(buffer_empty[1]),
    .B(_055_),
    .Y(_073_)
  );
  NOR _144_ (
    .A(_045_),
    .B(_055_),
    .Y(_074_)
  );
  NOR _145_ (
    .A(_046_),
    .B(_056_),
    .Y(_075_)
  );
  NOR _146_ (
    .A(_074_),
    .B(_075_),
    .Y(_076_)
  );
  NAND _147_ (
    .A(buffer_empty[1]),
    .B(_076_),
    .Y(_077_)
  );
  NAND _148_ (
    .A(_069_),
    .B(_077_),
    .Y(_078_)
  );
  NOT _149_ (
    .A(_078_),
    .Y(_079_)
  );
  NOR _150_ (
    .A(_073_),
    .B(_079_),
    .Y(_080_)
  );
  NOR _151_ (
    .A(_072_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _152_ (
    .A(_057_),
    .B(_081_),
    .Y(_082_)
  );
  NAND _153_ (
    .A(buffer_full[1]),
    .B(_076_),
    .Y(_083_)
  );
  NAND _154_ (
    .A(buffer_full[0]),
    .B(_049_),
    .Y(_084_)
  );
  NAND _155_ (
    .A(_083_),
    .B(_084_),
    .Y(_085_)
  );
  NOR _156_ (
    .A(buffer_full[1]),
    .B(_076_),
    .Y(_086_)
  );
  NOR _157_ (
    .A(_057_),
    .B(_086_),
    .Y(_087_)
  );
  NAND _158_ (
    .A(_085_),
    .B(_087_),
    .Y(_088_)
  );
  NOR _159_ (
    .A(almost_full_f),
    .B(_058_),
    .Y(_089_)
  );
  NAND _160_ (
    .A(_025_),
    .B(_057_),
    .Y(_090_)
  );
  NOR _161_ (
    .A(_029_),
    .B(_089_),
    .Y(_091_)
  );
  NAND _162_ (
    .A(reset_L),
    .B(_090_),
    .Y(_092_)
  );
  NAND _163_ (
    .A(_088_),
    .B(_091_),
    .Y(_093_)
  );
  NOR _164_ (
    .A(_082_),
    .B(_093_),
    .Y(almost_full_c)
  );
  NOR _165_ (
    .A(_029_),
    .B(_033_),
    .Y(state[0])
  );
  NOR _166_ (
    .A(_029_),
    .B(_038_),
    .Y(state[1])
  );
  NOR _167_ (
    .A(_082_),
    .B(_089_),
    .Y(_005_)
  );
  NOR _168_ (
    .A(_029_),
    .B(_090_),
    .Y(empty_c)
  );
  NOR _169_ (
    .A(_029_),
    .B(_005_),
    .Y(almost_empty_c)
  );
  NOR _170_ (
    .A(_058_),
    .B(_092_),
    .Y(_004_)
  );
  NAND _171_ (
    .A(_035_),
    .B(_039_),
    .Y(_006_)
  );
  NOR _172_ (
    .A(_033_),
    .B(_037_),
    .Y(_007_)
  );
  NOT _173_ (
    .A(_007_),
    .Y(_008_)
  );
  NOR _174_ (
    .A(_030_),
    .B(_008_),
    .Y(_009_)
  );
  NAND _175_ (
    .A(_030_),
    .B(_008_),
    .Y(_010_)
  );
  NAND _176_ (
    .A(reset_L),
    .B(_010_),
    .Y(_011_)
  );
  NOR _177_ (
    .A(_009_),
    .B(_011_),
    .Y(_002_[0])
  );
  NOR _178_ (
    .A(flop_rd[1]),
    .B(_009_),
    .Y(_012_)
  );
  NAND _179_ (
    .A(flop_rd[1]),
    .B(_009_),
    .Y(_013_)
  );
  NAND _180_ (
    .A(reset_L),
    .B(_013_),
    .Y(_014_)
  );
  NOR _181_ (
    .A(_012_),
    .B(_014_),
    .Y(_002_[1])
  );
  NAND _182_ (
    .A(_028_),
    .B(_041_),
    .Y(_015_)
  );
  NAND _183_ (
    .A(_006_),
    .B(_015_),
    .Y(_016_)
  );
  NOT _184_ (
    .A(_016_),
    .Y(_017_)
  );
  NOR _185_ (
    .A(_031_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _186_ (
    .A(flop_wr[0]),
    .B(_016_),
    .Y(_019_)
  );
  NOT _187_ (
    .A(_019_),
    .Y(_020_)
  );
  NAND _188_ (
    .A(reset_L),
    .B(_020_),
    .Y(_021_)
  );
  NOR _189_ (
    .A(_018_),
    .B(_021_),
    .Y(_003_[0])
  );
  NOR _190_ (
    .A(flop_wr[1]),
    .B(_018_),
    .Y(_022_)
  );
  NAND _191_ (
    .A(flop_wr[1]),
    .B(_018_),
    .Y(_023_)
  );
  NAND _192_ (
    .A(reset_L),
    .B(_023_),
    .Y(_024_)
  );
  NOR _193_ (
    .A(_022_),
    .B(_024_),
    .Y(_003_[1])
  );
  NOR _194_ (
    .A(_029_),
    .B(_090_),
    .Y(_001_)
  );
  NOR _195_ (
    .A(_082_),
    .B(_093_),
    .Y(_000_)
  );
  (* src = "fifo_cond.v:62" *)
  DFF _196_ (
    .C(clk),
    .D(error),
    .Q(error_c)
  );
  (* src = "fifo_cond.v:62" *)
  DFF _197_ (
    .C(clk),
    .D(_003_[0]),
    .Q(flop_wr[0])
  );
  (* src = "fifo_cond.v:62" *)
  DFF _198_ (
    .C(clk),
    .D(_003_[1]),
    .Q(flop_wr[1])
  );
  (* src = "fifo_cond.v:62" *)
  DFF _199_ (
    .C(clk),
    .D(_002_[0]),
    .Q(flop_rd[0])
  );
  (* src = "fifo_cond.v:62" *)
  DFF _200_ (
    .C(clk),
    .D(_002_[1]),
    .Q(flop_rd[1])
  );
  (* src = "fifo_cond.v:62" *)
  DFF _201_ (
    .C(clk),
    .D(_000_),
    .Q(almost_full_f)
  );
  (* src = "fifo_cond.v:62" *)
  DFF _202_ (
    .C(clk),
    .D(_001_),
    .Q(empty_f)
  );
  (* src = "fifo_cond.v:62" *)
  DFF _203_ (
    .C(clk),
    .D(_004_),
    .Q(full_f)
  );
  (* src = "fifo_cond.v:46" *)
  \$paramod\Ram\RAM_WIDTH=6\ADDR_SIZE=2  ram_FIFO (
    .addr_in(flop_wr),
    .addr_out(flop_rd),
    .clk(clk),
    .data_in(data_in),
    .data_out_c(data_out_c),
    .enable(enable2),
    .reset_L(reset_L),
    .state(state)
  );
  assign enable = 1'h1;
  assign full_out_c = 1'h0;
endmodule
